// src/frontend/Done.svelte
<StepHeader step="done"/>
<p>
  {$_("steps.done.introduction")}
</p>
{#if errors !== null && errors.length > 0}
  <p class="mdc-typography--subtitle2">
    {@html $_("steps.done.errors.introduction", {values: {link: '<a href="https://github.com/skaut/shared-drive-mover/issues" target="_blank">' + $_("steps.done.errors.github") + "</a>"}})}
  </p>
  <DataTable>
    <Head>
      <Row>
        <Cell>
          {$_("steps.done.errors.file")}
        </Cell>
        <Cell>
          {$_("steps.done.errors.message")}
        </Cell>
      </Row>
    </Head>
    <Body>
      {#each errors as error}
        <Row>
          <Cell>
            {error.file.join("/")}
          </Cell>
          <Cell>
            {error.error}
          </Cell>
        </Row>
      {/each}
    </Body>
  </DataTable>
{/if}

<script lang="ts">
  import {_} from "svelte-i18n";
  import DataTable, {Body, Cell, Head, Row} from "@smui/data-table"

  import StepHeader from "./StepHeader.svelte";

  import type { MoveError } from "../interfaces/MoveError";

  export let errors: Array<MoveError>|null = [];
</script>

<style lang="scss">
  @import "@material/typography/mdc-typography";
</style>

// src/frontend.vue/Done.vue
<template>
  <div>
    <p>
      {{ $t("done.description") }}
    </p>
    <div v-if="errors.length > 0">
      <p class="md-body-2">
        <md-icon class="md-accent">error</md-icon>
        <i18n path="done.errorHeader.text">
          <template #link>
            <a
              href="https://github.com/skaut/shared-drive-mover/issues"
              target="_blank"
              >{{ $t("done.errorHeader.github") }}</a
            >
          </template>
        </i18n>
      </p>
      <md-table>
        <md-table-row>
          <md-table-head> {{ $t("done.file") }} </md-table-head>
          <md-table-head> {{ $t("done.message") }} </md-table-head>
        </md-table-row>
        <md-table-row v-for="error in errors" :key="error.file">
          <md-table-cell> {{ error.file.join("/") }} </md-table-cell>
          <md-table-cell> {{ error.error }} </md-table-cell>
        </md-table-row>
      </md-table>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    errors: {
      type: Array,
      default: (): Array<string> => [],
    },
  },
});
</script>

<style scoped>
div {
  margin-top: 20px;
}
</style>
